#rest client test for backend

### Get all values
GET http://localhost:5000/user

### Get value by id
POST http://localhost:5000/login
content-type: application/json
{
    "email": "angga@gmail.com",
    "password": "angga123456"
}

### Create model
POST http://localhost:5000/login
content-type: application/json

{
   "email": "angga@gmail.com",
    "password": "angga123456"
}

### Update model
PUT http://localhost:5000/api/values/1
content-type: application/json

{
    "firstName": "David",
    "lastName": "Smith"
}

### Delete value
DELETE http://localhost:5000/api/values/1
 
