#rest client test for backend

### Get all values
GET http://localhost:5000/user

### Get value by id
GET http://localhost:5000/api/values/1

### Create model
POST http://localhost:5000/api/values
content-type: application/json

{
    "firstName": "John",
    "lastName": "Brown"
}

### Update model
PUT http://localhost:5000/api/values/1
content-type: application/json

{
    "firstName": "David",
    "lastName": "Smith"
}

### Delete value
DELETE http://localhost:5000/api/values/1
 
