#rest client test for backend

### Get all values
GET http://localhost:5000/user

### post users


### Create model
POST http://localhost:5000/power
content-type: application/json

{
    "health":5,
    "meals":3,
    "power":5
}

### Update model
PUT http://localhost:5000/api/values/1
content-type: application/json

{
    "firstName": "David",
    "lastName": "Smith"
}

### Delete value
DELETE http://localhost:5000/api/values/1
 
